Create the Dockerfile and associated scripts
kiwix/borg-backup pull request #1
Opened 2020-08-26 15:21 UTC by florentk

2020-08-26 17:24 UTC, rgaudin requested changes
Looks good, thank you. Made some minor inline comments.

2020-08-26 17:24 UTC, rgaudin commented on bin/entrypoint.sh
> +    echo "Initial backup ..."
I think this should be moved to a `@reboot` cron entry.

2020-08-26 17:24 UTC, rgaudin commented on bin/entrypoint.sh
> +    echo "Start Cron ..."
I think this should be moved to the `CMD` of the Dockerfile. This would allow the entrypoint to do only the setup and the actual tasks to be the main process that can be bypassed

```dockerfile
CMD ["cron", "-f"]
```

2020-08-26 17:24 UTC, rgaudin commented on bin/init_borgbase_repository.py
> +#!/usr/bin/python3
common:
* use [black](https://pypi.org/project/black/) formatting, so it's easier to maintain
* order imports as *standardlib*, empty line, *dependencies*

2020-08-26 17:24 UTC, rgaudin commented on bin/init_borgbase_repository.py
> +from borgbase_api_client.mutations import *
don't import `*` as it's harder to understand.

2020-08-26 17:24 UTC, rgaudin commented on bin/init_borgbase_repository.py
> +    time.sleep(2)
why do we need to sleep before starting?

2020-08-26 17:24 UTC, rgaudin commented on bin/init_borgbase_repository.py
> +    subprocess.call(["/root/.local/bin/borgmatic", "-c", BORGMATIC_CONFIG, "-v", "1", "init","--encryption", BORG_ENCRYPTION])
Do we need the full path to borgmatic? Prevents testing locally.

2020-08-26 17:24 UTC, rgaudin commented on bin/init_borgbase_repository.py
> +    main(BACKUP_NAME)
We should maybe check the environs and fail if missing?

2020-08-26 17:24 UTC, rgaudin commented on bin/init_borgbase_repository.py
> +        FILE.write("""
You can use f-strings as we're python3.6+ only

```py
f"some text {some_variable}"
```

2020-08-26 17:24 UTC, rgaudin commented on bin/init_borgbase_repository.py
> +        subprocess.run(["/usr/bin/ssh-keyscan","-H", hostname], stdout=outfile)
`/usr/bin/env ssh-keyscan` ?

2020-08-26 17:24 UTC, rgaudin commented on bin/init_borgbase_repository.py
> +    if len(repo_id) > 0 :
`if repo_id` works as well.

2020-09-05 16:11 UTC, kelson42 commented
@florentk Any news here?

2020-09-07 09:06 UTC, florentk commented on bin/init_borgbase_repository.py
> +    time.sleep(2)
yes is dirty, but if I init borgamatic immediatly, the command fail. Maybe make more sens if mode the sleep after create the repo.

2020-09-07 09:16 UTC, florentk commented on bin/init_borgbase_repository.py
> +        subprocess.run(["/usr/bin/ssh-keyscan","-H", hostname], stdout=outfile)
this prevent prompt when adding of hostname in known_hosts file

2020-09-07 11:41 UTC, rgaudin commented on bin/init_borgbase_repository.py
> +        subprocess.run(["/usr/bin/ssh-keyscan","-H", hostname], stdout=outfile)
Sorry I meant we could use `/usr/bin/env ssh-keyscan` instead of /usr/bin/ssh-keyscan as this binary is not in that location on all system/distro. Doesn't matter for docker but easier to test locally

2020-09-07 11:52 UTC, rgaudin commented on bin/init_borgbase_repository.py
> +    time.sleep(2)
OK ; then maybe add a comment mentioning the delay so we don't accidentally remove it later and have an hard to find bug

2020-09-08 09:20 UTC, florentk commented on bin/entrypoint.sh
> +    echo "Initial backup ..."
I think that when I add this in crontab, cron no run the command on start of docker container ...

2020-09-10 16:18 UTC, rgaudin commented on bin/entrypoint.sh
> +    echo "Initial backup ..."
you need to add the user running the command (`root`)

2020-09-10 16:19 UTC, rgaudin commented on bin/entrypoint.sh
> +    echo "Initial backup ..."
gonna add it after merging

2020-09-10 16:19 UTC, rgaudin approved these changes

2020-09-10 16:19 UTC, merged