add a tool to restore/extract a backup
kiwix/borg-backup pull request #37
Opened 2020-10-03 19:19 UTC by florentk

fix #24

2020-10-05 10:01 UTC, rgaudin requested changes
Thank you.

This doesn't work as the name is not exported.

Also, could we get rid of that confirmation message?

```
Remote: Warning: Permanently added the ECDSA host key for IP address '95.217.115.47' to the list of known hosts.
Warning: Attempting to access a previously unknown unencrypted repository!
Do you want to continue? [yN]
```

Otherwise listing and extracting work fine but for extracting we have zero output from borg so it would be better to have some log before/after extracting.

2020-10-05 11:49 UTC, florentk commented on bin/restore
> +# - BW_PASSWORD : BitWarden master password
We can remove "master"

2020-10-05 11:55 UTC, florentk commented
> This doesn't work as the name is not exported.

ohh, true ! 

> Remote: Warning: Permanently added the ECDSA host key for IP address '95.217.115.47' to the list of known hosts.
> Warning: Attempting to access a previously unknown unencrypted repository!
> Do you want to continue? [yN]
> ```

I look at this.

2020-10-06 09:30 UTC, rgaudin approved these changes
👍

2020-10-06 09:30 UTC, merged