Configure borgmatic periodicity
kiwix/borg-backup pull request #39
Opened 2020-10-06 10:29 UTC by florentk

Fix : 
 configure borgmatic periodicity #25
 make sure borgmatic commands don't overlap #26
 configure borgbase alertdays based on periodicity #27

2020-10-06 14:25 UTC, rgaudin commented on Dockerfile
> +ENV QUOTAS="2048"
What are those for? Why are those not documented?

2020-10-06 16:00 UTC, rgaudin requested changes
Thank you ; works fine but there are still a few concerns:

- it's not as flexible as the doc. So we can't close the periodicity ticket with that iteration
- `quota` and `region` are setup option and should be cli args
- `PERIODICITY` is used in setup as well to define alert. This won't work as we don't export it in `setup-new-repo` so it would default to what's in Dockerfile… Or needs to be set which doesn't make sense. We should have an optional `--alert-days` to set it.
- all of those quota/region/alert should be documented. Both briefly in Dockerfile obviously but also in the documentation. 
- `quota` should be singular (not `quotas`)

If you prefer, open a ticket listing documentation updates in french and I'll update the documentation from time to time

Currently we can set incoherent values like `--every 45d` that would render as

```
12 3 */45 * * root /usr/bin/flock
```

This would raise no error but will not run the command either.

2020-10-08 09:57 UTC, rgaudin requested changes
Thanks ; still a couple of issues:

- `--alert-days` require a number of days with a suffix. Why is that??? It already has the unit in the arg name… and you're stripping it out anyway.
- Why do we have a quota by default? Makes no sense. Default should be no quota. Users can set quota if they want. Also, when suggesting a size for quota, it'd be adequate to use non-binary values (2000 instead of 2048) as that's what borgmatic and borgbase use.

2020-10-08 12:38 UTC, florentk commented
> * `--alert-days` require a number of days with a suffix. Why is that??? It already has the unit in the arg name… and you're stripping it out anyway.
I wanted to make uniform with the backup command for perdiodicity, but we can remove the suffix.


> * Why do we have a quota by default? Makes no sense. Default should be no quota. Users can set quota if they want. Also, when suggesting a size for quota, it'd be adequate to use non-binary values (2000 instead of 2048) as that's what borgmatic and borgbase use.
Ok for no quota by default.

2020-10-08 13:03 UTC, rgaudin commented
> > * `--alert-days` require a number of days with a suffix. Why is that??? It already has the unit in the arg name… and you're stripping it out anyway.
> 
> @rgaudin I wanted to make uniform with the backup command for perdiodicity, but we can remove the suffix.

I don't think it matters. periodicity is used on backup only and alert on setup only. If we were able to have an `--alert-every 1w` where we'd accept suffixes, that'd wise.
But since we're forced to days and because it's a different concept, I prefer we choose clarity over harmonization for this.

2020-10-12 15:11 UTC, florentk commented
@rgaudin any news ?

2020-10-12 15:16 UTC, rgaudin commented
Ah comme le premier changement visible c'est le `ENV PERIODICITY="1d"` dans le Dockerfile que tu as oublié de changé, je n'avais pas fait gaffe que tu avais changé les alertes.
Je regarde des que c'est changé

2020-10-14 13:57 UTC, rgaudin approved these changes
merci

2020-10-14 13:57 UTC, merged