Allows to set retention params as env var
kiwix/borg-backup pull request #8
Opened 2020-09-23 19:15 UTC by florentk

resolve https://github.com/kiwix/borg-backup/issues/4

2020-09-24 09:45 UTC, rgaudin commented on README.md
> +
Pretty sure you'll also need the location/port of the server too

2020-09-24 09:49 UTC, rgaudin requested changes
I think we miss connection information to the databases. Has this been tested?
Keep in mind that this is gonna be a docker image companion to projects so even the default access won't work (`localhost:3306` for mysql)

2020-09-25 11:18 UTC, rgaudin commented
But but I have concerns about the example docker-compose:

- should be in an `examples/` folder
- use regular networking:
  - no `network_mode` rule
  - no `ports` rule
  - use `- DB_HOSTNAME=db`
  - use `DB_NAME=all` for tests
  - use `build:` rule instead of image (or use public image)

Also, please create your PR from branches in this repo instead of your fork so that we can contribute to it directly.

2020-09-25 11:46 UTC, florentk commented
> But but I have concerns about the example docker-compose:
> 
> * should be in an `examples/` folder

ok

> * use regular networking:
>   
>   * no `network_mode` rule
>   * use `- DB_HOSTNAME=db`

if only it was that simple, I try with this before use network_mode rule, but by default mysql database has not right to authorize connection from a other host that localhost ...

>   * no `ports` rule
>   * use `DB_NAME=all` for tests
>   * use `build:` rule instead of image (or use public image)
> 

ok

> Also, please create your PR from branches in this repo instead of your fork so that we can contribute to it directly.

ok

2020-09-25 11:51 UTC, rgaudin commented
It is that simple. I've tested it.

```sh
docker exec -it borg-backup_backup_1 bash
root@0941467c13ed:~# mysql -h db -uroot -proot
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 36
Server version: 8.0.21 MySQL Community Server - GPL

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
| test_db            |
+--------------------+
5 rows in set (0.001 sec)

MySQL [(none)]>
```

2020-09-25 12:16 UTC, florentk commented
> It is that simple. I've tested it.
> 
> ```shell
> docker exec -it borg-backup_backup_1 bash
> root@0941467c13ed:~# mysql -h db -uroot -proot
> Welcome to the MariaDB monitor.  Commands end with ; or \g.
> Your MySQL connection id is 36
> Server version: 8.0.21 MySQL Community Server - GPL
> 
> Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.
> 
> Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
> 
> MySQL [(none)]> show databases;
> +--------------------+
> | Database           |
> +--------------------+
> | information_schema |
> | mysql              |
> | performance_schema |
> | sys                |
> | test_db            |
> +--------------------+
> 5 rows in set (0.001 sec)
> 
> MySQL [(none)]>
> ```

so much the better, I don't know why yesterday it was complicated

2020-09-25 15:41 UTC, merged